

MatrixCalculator : matrix.o MatrixOperations.o 
		gcc matrix.o MatrixOperations.o -o MatrixCalculator

matrix.o : matrix.c
		gcc -c matrix.c -o matrix.o 

MatrixOperations.o : MatrixOperations.c MatrixOperations.h
		gcc -c MatrixOperations.c -o MatrixOperations.o

clean:
		rm -f matrix.o MatrixOperations.o